GET http://127.0.0.1:8000/api/categories HTTP/1.1

###

GET http://127.0.0.1:8000/api/subcategories HTTP/1.1 
###

GET http://127.0.0.1:8000/api/childcategories HTTP/1.1 
###


GET http://127.0.0.1:8000/api/shops HTTP/1.1 
###

GET http://127.0.0.1:8000/api/shopparents HTTP/1.1 
###

GET http://127.0.0.1:8000/api/products HTTP/1.1 
###

GET http://127.0.0.1:8000/api/users HTTP/1.1 
###

POST http://127.0.0.1:8000/api/categories HTTP/1.1
Content-Type: application/json

{
    "name" : "Watches"
}

###

POST http://127.0.0.1:8000/api/subcategories HTTP/1.1
Content-Type: application/json

{
    "category_id_fk" : "cat1",
    "name" : "Others"
}

###

POST http://127.0.0.1:8000/api/childcategories HTTP/1.1
Content-Type: application/json

{
    "sub_cat_id_fk" : "sub2",
    "name" : "blue jeans"
}

###

POST http://127.0.0.1:8000/api/shops HTTP/1.1
Content-Type: application/json

{
    "category_id_fk" : "cat2",
    "shop_name" : "GoodiesShop3",
    "logo" : "https://image.shutterstock.com/image-photo/surreal-image-african-elephant-wearing-260nw-1365289022.jpg"

}

###

POST http://127.0.0.1:8000/api/shopparents HTTP/1.1
Content-Type: application/json

{
        "shop_id_fk" : "shop1",
        "email" : "iftekhar2@gmail.com",
        "NID" : "2131233",
        "dob" : "2/3/1997",
        "address" : "dhaka",
        "first_name" : "Iftekhar",
        "last_name" : "Hyder",
		"number" : "01213123",
		"password" : "code",
		"type" : "staff"
}

###
POST http://127.0.0.1:8000/api/products HTTP/1.1
Content-Type: application/json

{

            "shop_id_fk" : "shop1",
            "name" : "photo",
            "description" : "rifats photo",
            "price" : 20,
            "product_category" : "Womens Clothes",
            "image1" : "https://storage.googleapis.com/oceanwide_web/media-dynamic/cache/widen_1600/media/default/0001/05/30627f237982b80399f5d2db0c8daeeea38a5950.jpeg",
            "image2" : "https://assets.vogue.in/photos/5dc3fda6ecd1c50008fe47d9/3:4/w_822,h_1096,c_limit/Sonam%20Kapoor%20in%20Sabyasachi%20sari.jpg",
            "image3" : "https://static.toiimg.com/photo/79679871/79679871.jpg?v=3",
            "discount" : 0
}

###

###
POST http://127.0.0.1:8000/api/users HTTP/1.1
Content-Type: application/json

{

            "email" : "iftekhar@gmail.com",
            "name" : "Iftekhar Hyder",
            "dob" : "4/3/1997",
            "address" : "Dhaka",
            "phone" : "012321321",
            "password" : "123"
}

###

GET http://127.0.0.1:8000/api/images/prod1/3 HTTP/1.1 
###

GET http://127.0.0.1:8000/api/logos/shop1 HTTP/1.1 
###

GET http://127.0.0.1:8000/api/shops/select/5/9 HTTP/1.1 

###


GET http://127.0.0.1:8000/api/products/select/1/2 HTTP/1.1 

###

GET http://127.0.0.1:8000/api/users/iftekhar@gmail.com/123


###

GET http://127.0.0.1:8000/api/shops/products/Walton

###

GET http://127.0.0.1:8000/api/shops/get/Walton
###

GET http://127.0.0.1:8000/api/products/random/4 HTTP/1.1 
###


GET http://127.0.0.1:8000/api/products/recent/3 HTTP/1.1


###
GET http://127.0.0.1:8000/api/productattributes HTTP/1.1

###
GET http://127.0.0.1:8000/api/colors HTTP/1.1

###

GET http://127.0.0.1:8000/api/sizes HTTP/1.1

###
POST http://127.0.0.1:8000/api/colors HTTP/1.1


###
POST http://127.0.0.1:8000/api/colors HTTP/1.1
Content-Type: application/json

{

            
            "value" : "#B81FBF"
}

###
POST http://127.0.0.1:8000/api/sizes HTTP/1.1
Content-Type: application/json

{

            
            "value" : "medium"
}

###
POST http://127.0.0.1:8000/api/productattributes HTTP/1.1
Content-Type: application/json

{

        "product_id_fk" : "prod2",
        "color_id_fk" :"color4",
        "size_id_fk" : "size1",
        "child_cat_id_fk" : "child1",
        "quantity" : 20
           
}

###
GET http://127.0.0.1:8000/api/getattributes/prod1 HTTP/1.1
